/* ── Allocation Mapper — structured investment allocation planner ────── */

// ==========================================
// TYPES
// ==========================================

export interface InvestmentPreferences {
  // Collected from conversation
  age: number;
  riskTolerance: "conservative" | "moderate" | "aggressive";
  investmentTimeline: "short" | "medium" | "long";     // <3yr, 3-10yr, 10yr+
  monthlyInvestmentBudget: number;
  currentPortfolioValue: number;
  hasRetirementAccount: boolean;
  interests: string[];                                   // Sectors/themes they care about
  excludes: string[];                                    // Sectors/companies to avoid
  incomeNeed: boolean;                                   // Need dividends?
  taxSituation: "taxable" | "tax_advantaged" | "both";
}

export interface AllocationPlan {
  // Plan metadata
  generatedAt: string;
  basedOn: string;                                       // "Your preferences and risk profile"
  disclaimer: string;

  // Suggested allocation framework
  assetAllocation: {
    stocks: { percentage: number; reason: string };
    bonds: { percentage: number; reason: string };
    cash: { percentage: number; reason: string };
    alternatives?: { percentage: number; reason: string };
  };

  // Within stocks — sector allocation
  sectorAllocation: {
    sector: string;
    percentage: number;
    reason: string;
    exampleETFs: { ticker: string; name: string; expenseRatio: number }[];
    analystConsensus?: string;                           // "Goldman and Morningstar rate overweight"
  }[];

  // Within bonds — type allocation
  bondAllocation: {
    type: string;                                        // "US Treasury", "Corporate", "Municipal"
    percentage: number;
    reason: string;
    exampleETFs: { ticker: string; name: string; expenseRatio: number; yield: number }[];
  }[];

  // Monthly investment schedule
  monthlyPlan: {
    account: string;                                     // "401k", "Roth IRA", "Taxable Brokerage"
    monthlyAmount: number;
    allocation: { ticker: string; name: string; percentage: number; dollarAmount: number }[];
    taxBenefit: string;                                  // "Pre-tax reduces taxable income" etc.
  }[];

  // Rebalancing schedule
  rebalancingFrequency: "quarterly" | "semi_annual" | "annual";
  rebalancingMethod: string;

  // Educational context for each choice
  educationalNotes: {
    topic: string;
    explanation: string;
    source?: string;
  }[];

  // Export format
  exportFormats: ("clipboard" | "notes" | "pdf" | "csv")[];
}

// ==========================================
// SYSTEM PROMPT INSTRUCTIONS
// ==========================================

export const ALLOCATION_MAPPER_INSTRUCTIONS = `
When a user wants help planning their investment allocation:

1. COLLECT preferences through conversation:
   - Age, risk tolerance, timeline, monthly budget
   - Do they need income (dividends) or growth?
   - Any sectors they love or want to avoid?
   - Tax situation (401k, IRA, taxable, mix)

2. BUILD the allocation framework:
   - Use standard age-based stock/bond split as starting point
   - Adjust for risk tolerance
   - Factor in their interests (but don't over-concentrate)

3. MAP TO SPECIFIC ETFs (not individual stocks):
   - Use low-cost index ETFs as defaults (VTI, VXUS, BND, etc.)
   - Only suggest sector ETFs if they expressed interest
   - Always show expense ratios — cost matters

4. INCLUDE analyst consensus where relevant:
   - "Analysts at Goldman and Fidelity currently rate tech overweight"
   - This is context, not recommendation

5. STRUCTURE the monthly plan:
   - Prioritize: employer match → Roth IRA → taxable
   - Show exact dollar amounts per fund per month
   - Account for tax efficiency (bonds in tax-advantaged, growth in taxable)

6. OUTPUT as an AllocationPlan JSON block

7. ADD a "copy to notes" formatted version:
   A clean, human-readable version they can paste into their phone notes,
   print out, or take to a financial advisor. Format:

   === MY INVESTMENT PLAN ===
   Generated by Agent Richy — [date]

   MONTHLY BUDGET: $XXX
   RISK PROFILE: [Conservative/Moderate/Aggressive]

   ASSET MIX:
   • Stocks: XX% ($XXX/month)
   • Bonds: XX% ($XXX/month)
   • Cash reserve: XX%

   WHERE TO INVEST:
   [Account] — $XXX/month
   • [ETF] ([Ticker]) — XX% — $XXX
   • [ETF] ([Ticker]) — XX% — $XXX

   REBALANCE: Every [X] months

   ⚠️ This is an organizational tool, not financial advice.
   Discuss with a licensed advisor before making changes.
   === END ===

CRITICAL RULES:
- This is an ORGANIZATIONAL tool, not advice
- Always recommend they discuss with a financial advisor
- Use ETFs, not individual stocks (more diversified, less risky to suggest)
- Show expense ratios — a 0.03% ETF vs 0.75% matters over decades
- Never say "you should" — say "based on your profile, a common approach is"
- Include the disclaimer ALWAYS
`;
