'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from 'recharts';
import ExportableCard from './ExportableCard';
import type { AllocationPlan } from '@/lib/allocationMapper';

/* ── Helpers ───────────────────────────────────────────────────────── */

function fmt(n: number): string {
  return n.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
}

function pct(n: number): string {
  return `${Math.round(n)}%`;
}

/* ── Animation variants ────────────────────────────────────────────── */

const stagger = {
  hidden: {},
  show: { transition: { staggerChildren: 0.06 } },
};

const fadeUp = {
  hidden: { opacity: 0, y: 12 },
  show: { opacity: 1, y: 0, transition: { duration: 0.35, ease: 'easeOut' } },
};

const collapse = {
  initial: { height: 0, opacity: 0 },
  animate: { height: 'auto', opacity: 1, transition: { duration: 0.25, ease: 'easeOut' } },
  exit: { height: 0, opacity: 0, transition: { duration: 0.2, ease: 'easeIn' } },
};

/* ── Chevron ───────────────────────────────────────────────────────── */

function Chevron({ open }: { open: boolean }) {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 16 16"
      fill="none"
      className={`text-muted transition-transform duration-200 ${open ? 'rotate-180' : ''}`}
    >
      <path
        d="M4 6L8 10L12 6"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

/* ── Donut chart colors ────────────────────────────────────────────── */

const DONUT_COLORS = ['#00E87B', '#3B82F6', '#A78BFA', '#F59E0B'];

/* ── Custom tooltip ────────────────────────────────────────────────── */

interface TooltipPayloadEntry {
  name: string;
  value: number;
  payload: { reason: string };
}

function DonutTooltip({
  active,
  payload,
}: {
  active?: boolean;
  payload?: TooltipPayloadEntry[];
}) {
  if (!active || !payload || payload.length === 0) return null;
  const d = payload[0];
  return (
    <div className="bg-bg border border-line rounded-lg px-3 py-2 text-xs shadow-lg max-w-[200px]">
      <p className="text-txt font-medium">{d.name}: {pct(d.value)}</p>
      <p className="text-muted mt-0.5">{d.payload.reason}</p>
    </div>
  );
}

/* ── Export builder ─────────────────────────────────────────────────── */

function buildExportData(plan: AllocationPlan) {
  const lines: string[] = [
    '=== MY INVESTMENT PLAN ===',
    `Generated by Agent Richy — ${new Date(plan.generatedAt).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`,
    '',
    'ASSET MIX:',
    `  • Stocks: ${pct(plan.assetAllocation.stocks.percentage)}`,
    `  • Bonds: ${pct(plan.assetAllocation.bonds.percentage)}`,
    `  • Cash: ${pct(plan.assetAllocation.cash.percentage)}`,
  ];

  if (plan.assetAllocation.alternatives) {
    lines.push(`  • Alternatives: ${pct(plan.assetAllocation.alternatives.percentage)}`);
  }

  lines.push('');

  if (plan.sectorAllocation.length > 0) {
    lines.push('SECTOR ALLOCATION:');
    for (const s of plan.sectorAllocation) {
      lines.push(`  ${s.sector}: ${pct(s.percentage)}`);
      for (const etf of s.exampleETFs) {
        lines.push(`    • ${etf.ticker} (${etf.name}) — ER: ${etf.expenseRatio}%`);
      }
    }
    lines.push('');
  }

  if (plan.monthlyPlan.length > 0) {
    lines.push('WHERE TO INVEST:');
    for (const acct of plan.monthlyPlan) {
      lines.push(`  ${acct.account} — ${fmt(acct.monthlyAmount)}/month`);
      for (const a of acct.allocation) {
        lines.push(`    • ${a.ticker} (${a.name}) — ${pct(a.percentage)} — ${fmt(a.dollarAmount)}`);
      }
      lines.push(`    Tax benefit: ${acct.taxBenefit}`);
    }
    lines.push('');
  }

  lines.push(`REBALANCE: ${plan.rebalancingFrequency.replace('_', '-')} — ${plan.rebalancingMethod}`);
  lines.push('');
  lines.push(`⚠️ ${plan.disclaimer}`);
  lines.push('=== END ===');

  // Clipboard: simpler version
  const clipLines = [
    `Investment Plan — ${pct(plan.assetAllocation.stocks.percentage)} stocks / ${pct(plan.assetAllocation.bonds.percentage)} bonds / ${pct(plan.assetAllocation.cash.percentage)} cash`,
  ];
  for (const acct of plan.monthlyPlan) {
    clipLines.push(`${acct.account}: ${fmt(acct.monthlyAmount)}/mo`);
    for (const a of acct.allocation) {
      clipLines.push(`  ${a.ticker} — ${pct(a.percentage)} (${fmt(a.dollarAmount)})`);
    }
  }

  return {
    clipboard: clipLines.join('\n'),
    formatted: lines.join('\n'),
  };
}

/* ── Main Component ────────────────────────────────────────────────── */

export default function AllocationPlanCard({
  plan,
}: {
  plan: AllocationPlan;
}) {
  const [notesOpen, setNotesOpen] = useState(false);

  // Build donut data
  const donutData = [
    { name: 'Stocks', value: plan.assetAllocation.stocks.percentage, reason: plan.assetAllocation.stocks.reason },
    { name: 'Bonds', value: plan.assetAllocation.bonds.percentage, reason: plan.assetAllocation.bonds.reason },
    { name: 'Cash', value: plan.assetAllocation.cash.percentage, reason: plan.assetAllocation.cash.reason },
    ...(plan.assetAllocation.alternatives
      ? [{ name: 'Alternatives', value: plan.assetAllocation.alternatives.percentage, reason: plan.assetAllocation.alternatives.reason }]
      : []),
  ].filter((d) => d.value > 0);

  return (
    <ExportableCard title="Investment Plan" exportData={buildExportData(plan)}>
      <motion.div
        initial="hidden"
        animate="show"
        variants={stagger}
        className="bg-card border border-line rounded-t-card overflow-hidden"
      >
        {/* ── 1. HEADER ───────────────────────────────────────────── */}
        <motion.div variants={fadeUp} className="bg-s1 rounded-t-card p-5">
          <p className="font-mono text-accent text-xs uppercase tracking-widest">
            ALLOCATION PLAN
          </p>
          <h3 className="text-xl font-bold text-txt mt-1">
            Your Investment Framework
          </h3>
          <p className="text-muted text-sm mt-1">
            Based on your risk profile and goals
          </p>
        </motion.div>

        <div className="p-5 space-y-5">
          {/* ── 2. ASSET ALLOCATION DONUT ──────────────────────────── */}
          <motion.div variants={fadeUp}>
            <p className="font-mono text-accent text-xs uppercase tracking-widest mb-3">
              ASSET MIX
            </p>

            <div className="flex items-center gap-6">
              {/* Donut chart */}
              <div className="w-36 h-36 shrink-0">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={donutData}
                      cx="50%"
                      cy="50%"
                      innerRadius={38}
                      outerRadius={60}
                      paddingAngle={3}
                      dataKey="value"
                      stroke="none"
                    >
                      {donutData.map((_, idx) => (
                        <Cell
                          key={idx}
                          fill={DONUT_COLORS[idx % DONUT_COLORS.length]}
                        />
                      ))}
                    </Pie>
                    <Tooltip content={<DonutTooltip />} />
                  </PieChart>
                </ResponsiveContainer>
              </div>

              {/* Legend */}
              <div className="space-y-2 flex-1">
                {donutData.map((d, idx) => (
                  <div key={d.name} className="flex items-center gap-2">
                    <div
                      className="w-3 h-3 rounded-sm shrink-0"
                      style={{ backgroundColor: DONUT_COLORS[idx % DONUT_COLORS.length] }}
                    />
                    <span className="text-txt text-sm font-medium">
                      {d.name}
                    </span>
                    <span className="text-accent text-sm font-mono ml-auto">
                      {pct(d.value)}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </motion.div>

          {/* ── 3. SECTOR ALLOCATION BARS ──────────────────────────── */}
          {plan.sectorAllocation.length > 0 && (
            <motion.div variants={fadeUp}>
              <p className="font-mono text-accent text-xs uppercase tracking-widest mb-3">
                SECTOR BREAKDOWN
              </p>
              <div className="space-y-3">
                {plan.sectorAllocation.map((sector) => (
                  <div key={sector.sector}>
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-off text-sm">{sector.sector}</span>
                      <span className="text-txt text-sm font-mono">
                        {pct(sector.percentage)}
                      </span>
                    </div>
                    {/* Bar */}
                    <div className="w-full h-2 bg-s2 rounded-full overflow-hidden">
                      <motion.div
                        initial={{ width: 0 }}
                        animate={{ width: `${sector.percentage}%` }}
                        transition={{ duration: 0.6, ease: 'easeOut', delay: 0.1 }}
                        className="h-full bg-accent rounded-full"
                      />
                    </div>
                    {/* ETFs */}
                    <div className="flex items-center gap-2 mt-1 flex-wrap">
                      {sector.exampleETFs.map((etf) => (
                        <span
                          key={etf.ticker}
                          className="bg-s2 text-off text-[10px] font-mono px-2 py-0.5 rounded"
                        >
                          {etf.ticker} ({etf.expenseRatio}%)
                        </span>
                      ))}
                    </div>
                    {sector.analystConsensus && (
                      <p className="text-muted text-xs mt-1">
                        📊 {sector.analystConsensus}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            </motion.div>
          )}

          {/* ── 4. MONTHLY PLAN CARDS ─────────────────────────────── */}
          {plan.monthlyPlan.length > 0 && (
            <motion.div variants={fadeUp}>
              <p className="font-mono text-accent text-xs uppercase tracking-widest mb-3">
                MONTHLY PLAN
              </p>
              <div className="space-y-3">
                {plan.monthlyPlan.map((acct) => (
                  <div
                    key={acct.account}
                    className="bg-s1 border border-line rounded-lg overflow-hidden"
                  >
                    {/* Account header */}
                    <div className="px-4 py-3 flex items-center justify-between">
                      <span className="text-txt font-medium">{acct.account}</span>
                      <span className="text-accent font-medium font-mono">
                        {fmt(acct.monthlyAmount)}/mo
                      </span>
                    </div>

                    {/* Allocation rows */}
                    <div className="border-t border-line divide-y divide-line/50">
                      {acct.allocation.map((a) => (
                        <div
                          key={a.ticker}
                          className="px-4 py-2.5 flex items-center justify-between"
                        >
                          <div>
                            <span className="text-off text-sm">{a.name}</span>
                            <span className="text-muted text-xs ml-2 font-mono">
                              {a.ticker}
                            </span>
                          </div>
                          <div className="text-right">
                            <span className="text-txt text-sm font-mono">
                              {fmt(a.dollarAmount)}
                            </span>
                            <span className="text-muted text-xs ml-2">
                              ({pct(a.percentage)})
                            </span>
                          </div>
                        </div>
                      ))}
                    </div>

                    {/* Tax benefit */}
                    <div className="px-4 py-2 border-t border-line bg-accent/5">
                      <p className="text-accent text-xs">💰 {acct.taxBenefit}</p>
                    </div>
                  </div>
                ))}
              </div>
            </motion.div>
          )}

          {/* ── 5. REBALANCING ────────────────────────────────────── */}
          <motion.div
            variants={fadeUp}
            className="bg-s1 border border-line rounded-lg p-4"
          >
            <p className="font-mono text-muted text-[11px] uppercase tracking-widest mb-1">
              REBALANCING
            </p>
            <p className="text-txt text-sm">
              {plan.rebalancingFrequency.replace('_', '-')} · {plan.rebalancingMethod}
            </p>
          </motion.div>

          {/* ── 6. EDUCATIONAL NOTES (collapsible) ────────────────── */}
          {plan.educationalNotes.length > 0 && (
            <motion.div
              variants={fadeUp}
              className="bg-card border border-line rounded-lg overflow-hidden"
            >
              <button
                onClick={() => setNotesOpen(!notesOpen)}
                className="w-full px-4 py-3 flex items-center justify-between cursor-pointer hover:bg-s1/50 transition-colors"
              >
                <div className="flex items-center gap-2">
                  <span className="text-txt font-medium">Learn More</span>
                  <span className="bg-accent/15 text-accent text-[10px] font-mono px-2 py-0.5 rounded">
                    {plan.educationalNotes.length}
                  </span>
                </div>
                <Chevron open={notesOpen} />
              </button>

              <AnimatePresence>
                {notesOpen && (
                  <motion.div
                    key="notes"
                    variants={collapse}
                    initial="initial"
                    animate="animate"
                    exit="exit"
                    className="overflow-hidden"
                  >
                    <div className="px-4 pb-4 space-y-3">
                      {plan.educationalNotes.map((note, i) => (
                        <div key={i} className="bg-s1 rounded-lg p-3">
                          <p className="text-txt text-sm font-medium">
                            {note.topic}
                          </p>
                          <p className="text-off text-sm mt-1">
                            {note.explanation}
                          </p>
                          {note.source && (
                            <p className="text-muted text-xs mt-1">
                              Source: {note.source}
                            </p>
                          )}
                        </div>
                      ))}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          )}

          {/* ── 7. DISCLAIMER ─────────────────────────────────────── */}
          <motion.div
            variants={fadeUp}
            className="bg-s1 border border-line rounded-lg p-3"
          >
            <p className="text-muted text-xs leading-relaxed">
              ⚠️ {plan.disclaimer}
            </p>
          </motion.div>
        </div>
      </motion.div>
    </ExportableCard>
  );
}
